/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-05-12 03:40:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<article>\r\n");
      out.write("\t<img class=\"imageSlides\" src=\"images/thesame1.png\" style=\"width:100%\">\r\n");
      out.write("  \t<img class=\"imageSlides\" src=\"images/thesame2.png\" style=\"width:100%\">\r\n");
      out.write("  \t<img class=\"imageSlides\" src=\"images/thesame3.png\" style=\"width:100%\">\r\n");
      out.write("  \t<img class=\"imageSlides\" src=\"images/thesame4.png\" style=\"width:100%\">\r\n");
      out.write("  \t<img class=\"imageSlides\" src=\"images/thesame5.png\" style=\"width:100%\">\r\n");
      out.write("</article>\r\n");
      out.write("<article>\r\n");
      out.write("\t<span id=\"text\">BEST SELLER</span><br>\r\n");
      out.write("\t<img class=\"products_image\" src=\"images/thesameBest1.png\" style=\"width:20%\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/thesameBest2.png\" style=\"width:20%\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/thesameBest3.png\" style=\"width:20%\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/thesameBest4.png\" style=\"width:20%\">\r\n");
      out.write("</article>\r\n");
      out.write("<section>\r\n");
      out.write("  \t\t<span style=\"margin-left:250px;margin-right:80px;font-size:18px;\">어반 에코 하라케케 크림</span>\r\n");
      out.write("  \t\t<span style=\"margin-left:120px;margin-right:0px;font-size:18px;\">커버 퍼펙션 팁 컨실러 02.리치 베이지</span>\r\n");
      out.write("  \t\t<span style=\"margin-left:150px;margin-right:0px;font-size:18px;\">에코 어스 파워 핑크 선크림 SPF50+ PA++++</span>\r\n");
      out.write("  \t\t<span style=\"margin-left:120px;margin-right:0px;font-size:18px;\">힐링 티 가든 그린티 클렌징 워터</span>\r\n");
      out.write("  \t\t<br><br>\r\n");
      out.write("  \t\t<span style=\"margin-left:300px;margin-right:80px;font-size:18px;\"><b>17,000원</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:310px;margin-right:80px;font-size:18px;\"><b>5,000원</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:330px;margin-right:80px;font-size:18px;\"><b>10,000원</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:300px;margin-right:80px;font-size:18px;\"><b>5,500원</b></span>\r\n");
      out.write("  \t\t<br><br><br><br>\r\n");
      out.write("  \t</section>\r\n");
      out.write("<article>\r\n");
      out.write("\t<span id=\"text\">NEW PRODUCTS</span><br>\r\n");
      out.write("\t<img class=\"products_image\" src=\"images/thesameNew1.png\" style=\"width:20%\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/thesameNew2.png\" style=\"width:20%\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/thesameNew3.png\" style=\"width:20%\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/thesameNew4.png\" style=\"width:20%\">\r\n");
      out.write("</article>\r\n");
      out.write("<section>\r\n");
      out.write("  \t\t<span style=\"margin-left:270px;margin-right:80px;font-size:18px;\">파워 앰플 안티 링클</span>\r\n");
      out.write("  \t\t<span style=\"margin-left:180px;margin-right:0px;font-size:18px;\">쓰리 엣지 스틱 파운데이션 21호</span>\r\n");
      out.write("  \t\t<span style=\"margin-left:140px;margin-right:0px;font-size:18px;\">쓰리 엣지 립스틱 인텟스 핏 RD01 원 모어 나잇</span>\r\n");
      out.write("  \t\t<span style=\"margin-left:110px;margin-right:0px;font-size:18px;\">미네랄 옴므 블랙 스포츠 선 스틱</span>\r\n");
      out.write("  \t\t<br><br>\r\n");
      out.write("  \t\t<span style=\"margin-left:320px;margin-right:80px;font-size:18px;\"><b>15,000원</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:310px;margin-right:80px;font-size:18px;\"><b>16,000원</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:310px;margin-right:80px;font-size:18px;\"><b>16,000원</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:290px;margin-right:80px;font-size:18px;\"><b>16,000원</b></span>\r\n");
      out.write("  \t\t<br><br><br><br>\r\n");
      out.write("  \t</section>\r\n");
      out.write("<article>\r\n");
      out.write("\t<span id=\"text\">Event</span><br>\r\n");
      out.write("\t<img class=\"products_image\" src=\"images/event1.jpg\" style=\"width:20%; height:500px; padding:0px 40px 0px 40px;\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/event2.jpg\" style=\"width:20%; height:500px; padding:0px 40px 0px 40px;\">\r\n");
      out.write("  \t<img class=\"products_image\" src=\"images/event3.png\" style=\"width:20%; height:500px; padding:0px 40px 0px 40px;\">\r\n");
      out.write("</article>\r\n");
      out.write("<section>\r\n");
      out.write("  \t\t<span style=\"margin-left:330px;margin-right:80px;font-size:18px;\"><b>더샘X세븐틴 하라케케 댄스 커버 이벤트</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:250px;margin-right:160px;font-size:18px;\"><b>첫 리뷰 이벤트</b></span>\r\n");
      out.write("  \t\t<span style=\"margin-left:280px;margin-right:0px;font-size:18px;\"><b>온라인 단독 GIFT</b></span>\r\n");
      out.write("  \t\t<br><br><br><br>\r\n");
      out.write("  \t</section>\r\n");
      out.write("<script src=\"main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
